name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_job: # 添加作业名称，比如 "deploy_job"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to the server.
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_NAME }}
          pass: ${{ secrets.REMOTE_PASS }}
          connect_timeout: 10s
          local: 'index.html*'
          remote: ${{ secrets.REMOTE_TARGET }}