# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    steps:
      - name: Deploy to the server.
      # 这里是通过Secure Copy Protocol (SCP) 发送到远程服务器上。可以在github编辑workflow下的yml文件,右侧会显示不同方式的用法。
        uses: cross-the-world/scp-pipeline@master
        with:
          # 这里是ip地址
          host: ${{ secrets.REMOTE_HOST }}
          # 这里是用户名(连接服务器的用户名)
          user: ${{ secrets.REMOTE_NAME }}
          # 这里是密码(连接服务器的密码)
          pass: ${{ secrets.REMOTE_PASS }}
          # 连接超时时长  不写默认是30s 
          connect_timeout: 10s
          # 要把那个文件部署到服务器上 这里我要部署的是dist下的所有文件。根据实际路径切换。如果是vitePress的话：docs/.vitepress/dist/*
          local: 'index.html'
          # 这里要部署到服务器的那个路径 example: /www/wwwroot/${xxx目录下} 以服务器的为准
          remote: ${{ secrets.REMOTE_TARGET }}